### ISSUE TITLE
Fix list of winners to use event content

### ISSUE THREAD

**Issue by Pugzy** [bolt-rip/ingame#6]
The winners are currently set from the match end event using `match.getWinners`  this winners array is sorted by "lead" proximity included and may not actually be representative of who is winning. 

The winners should be set based on the event which will require a rework of the `transition` method.

**Comment by Pablete1234** [comment]
PGM should be adding a forced victory condition for a team when one ends for a specific team, which is when this happens to start with. So a bit of investigation on that may be required. Essentially, getWinners should be returning the same as the event

After further investigation, this is the issue:

```java
        case FINISHED:
          calculateVictory(); // Winners must be calculated and saved prior to cancel.
          Set<Competitor> winners = competitors.getRank(0);
          getExecutor(MatchScope.RUNNING).shutdownNow();
          getCountdown().cancelAll();
          callEvent(new MatchFinishEvent(this, winners));
```
When PGM transitions to finished, the victory is calculated and essentially getWinners is called (`competitors.getRank(0)`).

However, right after that the countdown is cancelled, including the time limit. The time limit victory condition is ignored if end time isn't reached (you don't want it to determine a winner if you're only halfway thru the match, obviously) and because there's no longer a countdown at all, the timie limit victory condition is simply no longer ranking competitors any differently.

Time limit:
```java
  @Override
  public boolean isCompleted(Match match) {
    TimeLimitCountdown countdown = match.needModule(TimeLimitMatchModule.class).getCountdown();
    return countdown != null && match.getCountdown().isFinished(countdown);
  }

  @Override
  public int compare(Competitor a, Competitor b) {
    if (result != null && isCompleted(a.getMatch())) {
      return result.compare(a, b);
    } else {
      return 0;
    }
  }
```
The `isCompleted` method returns true at first, but will return false after the countdown is cancelled, because it's removed, so compare or isFinal will no longer act on it.


We should consider modifying time limit so that when the countdown finishes the time limit is locked to always affect the result, instead of ignoring it.

**Comment by Pugzy** [comment]
This was resolved in PGM? @Pablete1234 ?

**Comment by Pablete1234** [comment]
yes
